import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :to_do, ToDoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# HTTPS redirect is handled at Fly's edge (via `force_https = true` in
# fly.toml) — applying force_ssl in the app would also redirect Fly's
# internal HTTP health checks, infinite-looping at boot.

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
